### PR TITLE
Added Documentation for UI Componenets

### PR DESCRIPTION
**Pull request by shabaz39**
This PR adds MDX documentation for the UI components in the components folder, including usage examples, prop descriptions, and an overview page. It covers components like Accordion, Button, Dialog, and more, making integration easier for developers.

**Changes Made:**

- Added individual MDX files for each UI component with detailed documentation.
- Provided clear descriptions for each prop and usage examples for easy integration.
- Created an overview page summarizing the components' purpose and key features.

### CODE REVIEW

**Comment by nisabmohd** [comment]
@shabaz39 , I really appreciate your contribution.

However, I would like a single page that contains all the markdown elements, including standard markdown files such as headings, lists, blockquotes, code blocks (with `showLineNumbers` and line highlighting), and the tab component I'm using to switch code. It should also cover how to add images, links, the note component, and the stepper. This will help make everything clear for anyone who is going to use this, so only the necessary markdown custom components and standard markdown elements should be included. Documenting all components used in the project won't be useful.

I also want you to modify the "Get Started" page to include instructions on where the content should be placed, specifying that content files should be in the `.mdx` extension with the appropriate frontmatter. Additionally, please include details on how to configure routes, how to clone the GitHub repository, install dependencies using `npm i`, and add information about other versions in the "Get Started" section.

Thank you.

**Comment by nisabmohd** [comment]
The component.mdx should be one file with Google content and inside get started folder 

> @shabaz39 , I really appreciate your contribution.
> 
> However, I would like a single page that contains all the markdown elements, including standard markdown files such as headings, lists, blockquotes, code blocks (with `showLineNumbers` and line highlighting), and the tab component I'm using to switch code. It should also cover how to add images, links, the note component, and the stepper. This will help make everything clear for anyone who is going to use this, so only the necessary markdown custom components and standard markdown elements should be included. Documenting all components used in the project won't be useful.
> 
> I also want you to modify the "Get Started" page to include instructions on where the content should be placed, specifying that content files should be in the `.mdx` extension with the appropriate frontmatter. Additionally, please include details on how to configure routes, how to clone the GitHub repository, install dependencies using `npm i`, and add information about other versions in the "Get Started" section.
> 
> Thank you.

**Comment by shabaz39** [comment]
sure. will do.

**Comment by nisabmohd** [comment]
> sure. will do.

Please be free for content don't need to follow my template in other files it's just random stuff i pasted there with some scripts 😅. until it's understandable to anyone you can create it however. You can use quillbot for grammatical mistakes.

**Comment by shabaz39** [comment]
Key Changes:
 
1. Explanation of `.mdx` Files: Added a section explaining that documentation should be written in `.mdx` files with frontmatter metadata.
2. Route Configuration: Provided an example from the `routes-config.ts` file to explain how routes are created and how they link to the left navigation bar.
3. Route Processing: Explained how the recursive function works to ensure all routes are properly displayed.

**Comment by nisabmohd** [comment]
Its not what i needed. Hence closing this PR

**Pull request closed without merging**
